const SET_MARKED_TABS: string = "SET_MARKED_TABS";
const SET_MULTIPLE_MARKED_TABS: string = "SET_MULTIPLE_MARKED_TABS";
const CLEAR_ALL_MARKED_TABS: string = "CLEAR_ALL_MARKED_TABS";
const SET_TABS_SORT_ORDER: string = "SET_TABS_SORT_ORDER";
const SET_UP_TABS: string = "SET_UP_TABS";
const TOGGLE_EXPANSION: string = "TOGGLE_EXPANSION";

const CHANGE_TABS_VIEWMODE: string = "CHANGE_TABS_VIEWMODE";

export {
    SET_MARKED_TABS,
    SET_MULTIPLE_MARKED_TABS,
    CLEAR_ALL_MARKED_TABS,
    SET_TABS_SORT_ORDER,
    SET_UP_TABS,
    TOGGLE_EXPANSION,
    CHANGE_TABS_VIEWMODE
}