const CHANGE_PERFORMANCE_NOTIFICATION: string = "CHANGE_PERFORMANCE_NOTIFICATION";
const CHANGE_DUPLICATION_WARNING: string = "CHANGE_DUPLICATION_WARNING";
const CHANGE_FOLDER_LAUNCH: string = "CHANGE_FOLDER_LAUNCH";
const CHANGE_CANCELLATION_WARNING: string = "CHANGE_CANCELLATION_WARNING";
const CHANGE_REMOVAL_WARNING: string = "CHANGE_REMOVAL_WARNING";
const CHANGE_ERROR_LOG_SETTING: string = "CHANGE_ERROR_LOG_SETTING";
const READ_ALL_PLUGIN_SETTINGS: string = "READ_ALL_PLUGIN_SETTINGS";

export {
    CHANGE_CANCELLATION_WARNING,
    CHANGE_DUPLICATION_WARNING,
    CHANGE_ERROR_LOG_SETTING,
    CHANGE_REMOVAL_WARNING,
    CHANGE_PERFORMANCE_NOTIFICATION,
    CHANGE_FOLDER_LAUNCH,
    READ_ALL_PLUGIN_SETTINGS
}